### ISSUE TITLE
Opensips As Registrar

### ISSUE THREAD

**Issue by hasanr68** [sem32/freeswitch-ApplePushNotification#10]
Hi there.
Just came across this. We are using Opensips as the registrar - would this project work in that scenario? Any one tried it?

**Comment by sem32** [comment]
Hi
This module won't work for your case. It based on logic on registration on side Freeswitch.
Kamailio has module [TSILO](https://kamailio.org/docs/modules/5.0.x/modules/tsilo.html) which could do what you need. You could try to find something similar for OpenSips

**Comment by hasanr68** [comment]
Alright - thanks a lot.
