### ISSUE TITLE
Cannot run ./automake. "configure.ac" is require

### ISSUE THREAD

**Issue by rsml** [sem32/freeswitch-ApplePushNotification#3]
I installed Freeswitch from source on a minimal Debian VM.

When I run
```
cd /usr/src/freeswitch/src/mod/endpoints/mod_apn
automake
```

I get:
`"automake: error: 'configure.ac' is required"`

I tried to use the configure.ac from /usr/src/freeswitch/configure.ac and inside /usr/src/freeswitch/libs/sofia-sip/configure.ac but wasn't successful.

**Comment by sem32** [comment]
Hi!
You have to start automake in /usr/src/freeswitch directory after add 'src/mod/endpoints/mod_apn/Makefile' near src/mod/endpoints/mod_sofia/Makefile in AC_CONFIG_FILES array section of file /usr/src/freeswitch/configure.ac

Try to use next steps:
Add to modules.conf parameter for build mod_apn
echo 'endpoints/mod_apn' >> modules.conf
Add to configure.ac (in  /usr/src/freeswitch/configure.ac) configuration for create Makefile for mod_apn (AC_CONFIG_FILES array section)
$ sed -i '/src\/mod\/endpoints\/mod_sofia\/Makefile/a src\/mod\/endpoints\/mod_apn\/Makefile' configure.ac
Start automake from directory  /usr/src/freeswitch

**Comment by rsml** [comment]
Thank you very much. It's working now 😄

**Comment by Alessandrog72** [comment]
Hello i try to use this procedure

but 

sed -i '/src/mod/applications/mod_dialogflow/Makefile/a src/mod/applications/mod_dialogflow/Makefile' configure.ac

i riceved  
sed: espressione -e #1, carattere 6: comando sconosciuto: `m'

why? 

Thanks Alessandro
