### ISSUE TITLE
push notification not sent when call made to endpoint

### ISSUE THREAD

**Issue by devopsec** [sem32/freeswitch-ApplePushNotification#6]
Push notification works when sending via apn-pusher or mod_apn via the fs_cli interface.
When an invite comes in to freeswitch mod_apn fails to send push notification.

working apn-pusher test (cert and token stored in variable)

```
apn-pusher -c ${CERTBUNDLE} -m 'Test AppleNotification' -t ${TOKEN} -v -p -d
```

working mod_apn test (cert and token stored in variable)

```
fs_cli -x 'apn {"app_id":"'${APPID}'","type":"voip","payload":{"body":"test","sound":"default","custom":[{"name":"number","value":1},{"name":"content_available","value":true}],"image":"","category":"VoIP"},"tokens":["'${TOKEN}'","'${TOKEN}'"]}' -d 7
```

Errors when actual invite comes in:

```
2019-04-24 17:29:04.969154 [ERR] mod_apn.c:86 ======>[apn] Unable to create binary message: alert message text or key used to get a localized alert-message string or content-available flag must be set (errno: 9021)
2019-04-24 17:29:04.969154 [DEBUG] mod_apn.c:375 CARUSTO. Could not send APN: alert message text or key used to get a localized alert-message string or content-available flag must be set (errno: 9021)
```

And in the code we can find these calls:

https://github.com/sem32/freeswitch-ApplePushNotification/blob/master/mod_apn/mod_apn.c#L377

That seem to fail when creating the binary message

https://github.com/sem32/freeswitch-ApplePushNotification/blob/ed0af7cd362de0c20edddc51e7a7cee36eeb6260/libcapn/src/library/apn.c#L291

This is the errno code we are getting which does not make sense because we are setting this value in the payload already:

https://github.com/sem32/freeswitch-ApplePushNotification/blob/ed0af7cd362de0c20edddc51e7a7cee36eeb6260/libcapn/src/library/apn.h#L114

The same occurs if we change the payload in the following line(to include alert parameter):

https://github.com/sem32/freeswitch-ApplePushNotification/blob/master/mod_apn/mod_apn.c#L1181

**Comment by sipvoip** [comment]
Did you find a solution? I am having the same problem.

**Comment by sem32** [comment]
closed, due to lib capn is not used anymore
