### ISSUE TITLE
Issue building on Centos 8

### ISSUE THREAD

**Issue by sipvoip** [sem32/freeswitch-ApplePushNotification#7]
Scanning dependencies of target capn
[ 47%] Building C object CMakeFiles/capn.dir/src/library/apn_memory.c.o
[ 52%] Building C object CMakeFiles/capn.dir/src/library/apn.c.o
/usr/src/ApplePushNotification/libcapn/src/library/apn.c: In function ‘apn_feedback’:
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:405:5: error: unknown type name ‘fd_set’; did you mean ‘sk_set’?
     fd_set read_set;
     ^~~~~~
     sk_set
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:12: error: variable ‘timeout’ has initializer but incomplete type
     struct timeval timeout = {3, 0};
            ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:31: warning: excess elements in struct initializer
     struct timeval timeout = {3, 0};
                               ^
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:31: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:34: warning: excess elements in struct initializer
     struct timeval timeout = {3, 0};
                                  ^
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:34: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:20: error: storage size of ‘timeout’ isn’t known
     struct timeval timeout = {3, 0};
                    ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:419:9: warning: implicit declaration of function ‘FD_ZERO’ [-Wimplicit-function-declaration]
         FD_ZERO(&read_set);
         ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:420:9: warning: implicit declaration of function ‘FD_SET’; did you mean ‘F_SETFL’? [-Wimplicit-function-declaration]
         FD_SET(ctx->sock, &read_set);
         ^~~~~~
         F_SETFL
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:422:31: warning: implicit declaration of function ‘select’; did you mean ‘execl’? [-Wimplicit-function-declaration]
         int select_returned = select(ctx->sock + 1, &read_set, NULL, NULL, &timeout);
                               ^~~~~~
                               execl
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:435:13: warning: implicit declaration of function ‘FD_ISSET’; did you mean ‘AF_INET’? [-Wimplicit-function-declaration]
         if (FD_ISSET(ctx->sock, &read_set)) {
             ^~~~~~~~
             AF_INET
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:20: warning: unused variable ‘timeout’ [-Wunused-variable]
     struct timeval timeout = {3, 0};
                    ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c: In function ‘__apn_send_binary_message’:
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:708:5: error: unknown type name ‘fd_set’; did you mean ‘sk_set’?
     fd_set write_set, read_set;
     ^~~~~~
     sk_set
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:12: error: variable ‘timeout’ has initializer but incomplete type
     struct timeval timeout = {10, 0};
            ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:31: warning: excess elements in struct initializer
     struct timeval timeout = {10, 0};
                               ^~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:31: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:35: warning: excess elements in struct initializer
     struct timeval timeout = {10, 0};
                                   ^
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:35: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:20: error: storage size of ‘timeout’ isn’t known
     struct timeval timeout = {10, 0};
                    ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:20: warning: unused variable ‘timeout’ [-Wunused-variable]
/usr/src/ApplePushNotification/libcapn/src/library/apn.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-pointer-bool-conversion’
make[2]: *** [CMakeFiles/capn.dir/build.make:76: CMakeFiles/capn.dir/src/library/apn.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/capn.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[  8%] Built target libcapn-config
[ 43%] Built target jansson
[ 47%] Building C object CMakeFiles/capn.dir/src/library/apn.c.o
/usr/src/ApplePushNotification/libcapn/src/library/apn.c: In function ‘apn_feedback’:
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:405:5: error: unknown type name ‘fd_set’; did you mean ‘sk_set’?
     fd_set read_set;
     ^~~~~~
     sk_set
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:12: error: variable ‘timeout’ has initializer but incomplete type
     struct timeval timeout = {3, 0};
            ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:31: warning: excess elements in struct initializer
     struct timeval timeout = {3, 0};
                               ^
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:31: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:34: warning: excess elements in struct initializer
     struct timeval timeout = {3, 0};
                                  ^
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:34: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:20: error: storage size of ‘timeout’ isn’t known
     struct timeval timeout = {3, 0};
                    ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:419:9: warning: implicit declaration of function ‘FD_ZERO’ [-Wimplicit-function-declaration]
         FD_ZERO(&read_set);
         ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:420:9: warning: implicit declaration of function ‘FD_SET’; did you mean ‘F_SETFL’? [-Wimplicit-function-declaration]
         FD_SET(ctx->sock, &read_set);
         ^~~~~~
         F_SETFL
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:422:31: warning: implicit declaration of function ‘select’; did you mean ‘execl’? [-Wimplicit-function-declaration]
         int select_returned = select(ctx->sock + 1, &read_set, NULL, NULL, &timeout);
                               ^~~~~~
                               execl
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:435:13: warning: implicit declaration of function ‘FD_ISSET’; did you mean ‘AF_INET’? [-Wimplicit-function-declaration]
         if (FD_ISSET(ctx->sock, &read_set)) {
             ^~~~~~~~
             AF_INET
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:406:20: warning: unused variable ‘timeout’ [-Wunused-variable]
     struct timeval timeout = {3, 0};
                    ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c: In function ‘__apn_send_binary_message’:
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:708:5: error: unknown type name ‘fd_set’; did you mean ‘sk_set’?
     fd_set write_set, read_set;
     ^~~~~~
     sk_set
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:12: error: variable ‘timeout’ has initializer but incomplete type
     struct timeval timeout = {10, 0};
            ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:31: warning: excess elements in struct initializer
     struct timeval timeout = {10, 0};
                               ^~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:31: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:35: warning: excess elements in struct initializer
     struct timeval timeout = {10, 0};
                                   ^
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:35: note: (near initialization for ‘timeout’)
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:20: error: storage size of ‘timeout’ isn’t known
     struct timeval timeout = {10, 0};
                    ^~~~~~~
/usr/src/ApplePushNotification/libcapn/src/library/apn.c:709:20: warning: unused variable ‘timeout’ [-Wunused-variable]
/usr/src/ApplePushNotification/libcapn/src/library/apn.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-pointer-bool-conversion’
make[2]: *** [CMakeFiles/capn.dir/build.make:76: CMakeFiles/capn.dir/src/library/apn.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:179: CMakeFiles/capn.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[root@as2-east ApplePushNotification]#

**Comment by Sfinx** [comment]
Try this patch, but the libcapn using too old libssl-dev (1.0.x) so it must be installed too:

```
diff --git a/libcapn/src/library/apn.c b/libcapn/src/library/apn.c
index d3e1b0c..651f7cb 100644
--- a/libcapn/src/library/apn.c
+++ b/libcapn/src/library/apn.c
@@ -20,6 +20,7 @@
  * THE SOFTWARE.
  */
 
+#include <sys/time.h>
 #include "apn_platform.h"
 
 #include <errno.h>
```
