### ISSUE TITLE
Can we make this generic for both APN and FCM

### ISSUE THREAD

**Issue by nikpakar** [sem32/freeswitch-ApplePushNotification#8]
Very nice and perfect approach for push notification in fs.

Is it possible to make this generic to support both APN and FCM ?

We can insert another parameter to contact uri i.e. pn-type=apn or fcm

**Comment by sem32** [comment]
Hi @nikpakar !

I thought  about your question and didn't find suitable library, like libapn for do the same for fcm.
So, I decided to rewrite mod_apn with using libcurl for send http request to external push service, which can support any kinds of platforms and configurations, certificates and different applications and so on. 

So, currently I pushed new version to master branch.
Thank you, and sorry for long delay for answer

**Comment by sem32** [comment]
You can start to use current version
